---
- name: Update Repositories
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install packages
  apt:
    state: present
    name:
      - htop
      - python3-pip
      - avahi-daemon
      - libnss-mdns
      - default-jre

- name: Update pip
  pip:
    name: pip
    state: latest